In [1]:
import pandas as pd
import numpy as np
from influxdb_client import InfluxDBClient

In [ ]:
client = InfluxDBClient(url="http://labplenk.hof-university.de:8086", token="MeinSuperSicheresAdminToken123", org="mein-zuhause")

In [3]:
query = f"""from(bucket: "system-metriken")
    |> range(start: -5m)
    |> filter(fn: (r) => r["_measurement"] == "disk")
    |> filter(fn: (r) => r["_field"] == "used_percent")"""

In [4]:
tables = client.query_api().query_data_frame(query, org="mein-zuhause")

/opt/conda/lib/python3.12/site-packages/influxdb_client/client/warnings.py:31: MissingPivotFunction: The query doesn't contains the pivot() function.

The result will not be shaped to optimal processing by pandas.DataFrame. Use the pivot() function by:

    from(bucket: "system-metriken")
    |> range(start: -5m)
    |> filter(fn: (r) => r["_measurement"] == "disk")
    |> filter(fn: (r) => r["_field"] == "used_percent") |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")

You can disable this warning by:
    import warnings
    from influxdb_client.client.warnings import MissingPivotFunction

    warnings.simplefilter("ignore", MissingPivotFunction)

For more info see:
    - https://docs.influxdata.com/resources/videos/pivots-in-flux/
    - https://docs.influxdata.com/flux/latest/stdlib/universe/pivot/
    - https://docs.influxdata.com/flux/latest/stdlib/influxdata/influxdb/schema/fieldsascols/

  warnings.warn(message, MissingPivotFunction)

In [5]:
display(tables)

,result,table,_start,_stop,_time,_value,_field,_measurement,device,fstype,host,mode,path
0,_result,0,2026-10-17 13:56:08.263207+00:00,2026-10-17 14:01:08.263207+00:00,2026-10-17 13:56:10+00:00,0.217992,used_percent,disk,mapper/ubuntu--vg-lv--0,ext4,f6eafa1d992d,ro,/etc/calculate_timestamps.star
1,_result,0,2026-10-17 13:56:08.263207+00:00,2026-10-17 14:01:08.263207+00:00,2026-10-17 13:56:20+00:00,0.217992,used_percent,disk,mapper/ubuntu--vg-lv--0,ext4,f6eafa1d992d,ro,/etc/calculate_timestamps.star
2,_result,0,2026-10-17 13:56:08.263207+00:00,2026-10-17 14:01:08.263207+00:00,2026-10-17 13:56:30+00:00,0.217995,used_percent,disk,mapper/ubuntu--vg-lv--0,ext4,f6eafa1d992d,ro,/etc/calculate_timestamps.star
3,_result,0,2026-10-17 13:56:08.263207+00:00,2026-10-17 14:01:08.263207+00:00,2026-10-17 13:56:40+00:00,0.217998,used_percent,disk,mapper/ubuntu--vg-lv--0,ext4,f6eafa1d992d,ro,/etc/calculate_timestamps.star
4,_result,0,2026-10-17 13:56:08.263207+00:00,2026-10-17 14:01:08.263207+00:00,2026-10-17 13:56:50+00:00,0.217998,used_percent,disk,mapper/ubuntu--vg-lv--0,ext4,f6eafa1d992d,ro,/etc/calculate_timestamps.star
...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,_result,5,2026-10-17 13:56:08.263207+00:00,2026-10-17 14:01:08.263207+00:00,2026-10-17 14:00:20+00:00,11.508466,used_percent,disk,mapper/ubuntu--vg-ubuntu--lv,ext4,f6eafa1d992d,rw,/etc/resolv.conf
176,_result,5,2026-10-17 13:56:08.263207+00:00,2026-10-17 14:01:08.263207+00:00,2026-10-17 14:00:30+00:00,11.508466,used_percent,disk,mapper/ubuntu--vg-ubuntu--lv,ext4,f6eafa1d992d,rw,/etc/resolv.conf
177,_result,5,2026-10-17 13:56:08.263207+00:00,2026-10-17 14:01:08.263207+00:00,2026-10-17 14:00:40+00:00,11.508470,used_percent,disk,mapper/ubuntu--vg-ubuntu--lv,ext4,f6eafa1d992d,rw,/etc/resolv.conf
178,_result,5,2026-10-17 13:56:08.263207+00:00,2026-10-17 14:01:08.263207+00:00,2026-10-17 14:00:50+00:00,11.508470,used_percent,disk,mapper/ubuntu--vg-ubuntu--lv,ext4,f6eafa1d992d,rw,/etc/resolv.conf
179,_result,5,2026-10-17 13:56:08.263207+00:00,2026-10-17 14:01:08.263207+00:00,2026-10-17 14:01:00+00:00,11.508470,used_percent,disk,mapper/ubuntu--vg-ubuntu--lv,ext4,f6eafa1d992d,rw,/etc/resolv.conf

In [ ]:
timeRange = "|> range(start: 2026-10-06T10:30:28.9321Z, stop: 2026-10-06T16:30:28.9321Z)"

In [7]:
waMaQuery = f"""from(bucket: "wama-daten")
    {timeRange} |> filter(fn: (r) => r._measurement == "WaMa") |> pivot(rowKey:["_time"],
    columnKey: ["_field"],
    valueColumn: "_value")"""
waMaData = client.query_api().query_data_frame(waMaQuery)

In [8]:
waMaData

,result,table,_start,_stop,_time,_measurement,host,src,active,analogIn0,flagWord4,inputWord0,outputWord0,remainingTime,stepNr
0,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:25:54.712331+00:00,WaMa,f6eafa1d992d,PLC,False,-1,33,16384,0,200000,1
1,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:25:55.209419+00:00,WaMa,f6eafa1d992d,PLC,False,-1,33,16384,0,200000,1
2,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:44.210885+00:00,WaMa,f6eafa1d992d,PLC,False,-1,33,16384,0,200000,1
3,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:44.710254+00:00,WaMa,f6eafa1d992d,PLC,False,-1,33,16384,0,200000,1
4,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:45.210166+00:00,WaMa,f6eafa1d992d,PLC,False,-1,33,16384,0,200000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2930,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:56:08.214266+00:00,WaMa,f6eafa1d992d,PLC,False,-1,33,17408,0,200000,1
2931,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:56:08.714397+00:00,WaMa,f6eafa1d992d,PLC,False,-1,33,17408,0,200000,1
2932,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:56:09.214167+00:00,WaMa,f6eafa1d992d,PLC,False,-1,33,17408,0,200000,1
2933,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:56:09.714683+00:00,WaMa,f6eafa1d992d,PLC,False,-1,33,17408,0,200000,1
2934,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:56:10.214485+00:00,WaMa,f6eafa1d992d,PLC,False,-1,33,17408,0,200000,1

In [9]:
vibrationQuery = f"""from(bucket: "wama-daten")
    {timeRange} |> filter(fn: (r) => r._measurement == "tail") |> pivot(rowKey:["_time"], 
    columnKey: ["_field"], valueColumn: "_value")"""

vibrationData = client.query_api().query_data_frame(vibrationQuery)

In [ ]:
vibrationData = vibrationData[0]

In [11]:
vibrationData

,result,table,_start,_stop,_time,_measurement,host,path,sensor_id,xAxis_438,yAxis_438,zAxis_438
0,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:21+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,-0.002736,0.003148,0.012469
1,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:21.005000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,0.004100,-0.008571,0.000262
2,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:21.010000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,0.004100,-0.004176,-0.000226
3,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:21.015000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,-0.000295,0.006078,0.002703
4,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:21.020000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,0.002635,0.000218,-0.000226
...,...,...,...,...,...,...,...,...,...,...,...,...
295675,_result,307,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:57:13.775000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,0.000425,0.003466,0.003398
295676,_result,307,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:57:13.780000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,-0.003970,-0.001905,0.005351
295677,_result,307,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:57:13.785000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,-0.002505,-0.007276,0.000468
295678,_result,307,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:57:13.790000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,-0.001528,0.001513,-0.000020
295679,_result,307,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:57:13.795000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,-0.004458,0.003466,0.008769

In [12]:
print(f"PLC Stream: {len(waMaData)} rows | {waMaData._time.min()} to {waMaData._time.max()}")

PLC Stream: 2935 rows | 2026-08-19 13:25:54.712331+00:00 to 2026-08-19 13:56:10.214485+00:00

In [13]:
print(f"Vibration Stream: {len(vibrationData)} rows | {vibrationData._time.min()} to {vibrationData._time.max()}")

Vibration Stream: 295680 rows | 2026-08-19 13:31:21+00:00 to 2026-08-19 13:57:13.795000+00:00

In [14]:
columnsOfInterest = ['active', 'analogIn0', 'flagWord4', 'inputWord0', 'outputWord0', 'remainingTime', 'stepNr']
for c in columnsOfInterest:
    print(f"{c}\t{waMaData[c].unique()}")

active	[False  True]
analogIn0	[-1 24 36  6 49]
flagWord4	[    33   6274   4098   8194  16386 -32766      2]
inputWord0	[16384 17408 17664]
outputWord0	[     0   3072  18432   2048 -30720  10240 -22528   2304]
remainingTime	[200000 199654 199154 ...  14768  14268  13768]
stepNr	[ 1  6  7  8  9 10  3  4  5]

In [15]:
binaryColumnsToFix = ["inputWord0", "outputWord0", "flagWord4"]

for c in binaryColumnsToFix:
    waMaData[c] = waMaData[c].astype(int)

for c in binaryColumnsToFix:
    print(f"{c}\t{waMaData[c].unique()}")

inputWord0	[16384 17408 17664]
outputWord0	[     0   3072  18432   2048 -30720  10240 -22528   2304]
flagWord4	[    33   6274   4098   8194  16386 -32766      2]

In [ ]:
measurementsQuery = """
import "influxdata/influxdb/schema"

schema.measurements(bucket: "wama-daten")
"""

measurements = client.query_api().query_data_frame(measurementsQuery)

print(measurements)

In [16]:
cycleDescriptionQuery = f"""from(bucket: "wama-daten")
    {timeRange} |> filter(fn: (r) => r._measurement == "cycle_description") |> pivot(rowKey:["_time"], 
    columnKey: ["_field"], valueColumn: "_value")"""

cycleDescriptionData = client.query_api().query_data_frame(cycleDescriptionQuery)

In [17]:
cycleDescriptionData

,result,table,_start,_stop,_time,_measurement,source,machine_cycle,note,sensor_438,sensor_620
0,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:10:56.853535+00:00,cycle_description,OperatorInput,normal,Just a test outside a cycle to verify that inf...,machine drum,machine drum
1,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:35:33.408042+00:00,cycle_description,OperatorInput,normal,WashSpeed: 50% \r\nSpinSpeed: 75%\r\nProgramme...,machine drum,machine body
2,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:39:22.525799+00:00,cycle_description,OperatorInput,normal,WashSpeed: 50% \r\nSpinSpeed: 75%\r\nProgramme...,machine drum,machine body
3,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:45:55.489128+00:00,cycle_description,OperatorInput,anormal,WashSpeed: 50% \r\nSpinSpeed: 75%\r\nProgramme...,machine drum,machine body
4,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:52:32.859832+00:00,cycle_description,OperatorInput,anormal,WashSpeed: 50% \r\nSpinSpeed: 100%\r\nProgramm...,machine drum,machine body

In [18]:
vibrationData = vibrationData.sort_values(by="_time").reset_index(drop=True)
waMaData = waMaData.sort_values(by="_time").reset_index(drop=True)

In [19]:
data = pd.merge_asof(vibrationData, waMaData, on="_time", direction="backward", tolerance=pd.Timedelta("2s"))

In [20]:
display(data)

,result_x,table_x,_start_x,_stop_x,_time,_measurement_x,host_x,path,sensor_id,xAxis_438,...,_measurement_y,host_y,src,active,analogIn0,flagWord4,inputWord0,outputWord0,remainingTime,stepNr
0,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:21+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,-0.002736,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:21.005000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,0.004100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:21.010000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,0.004100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:21.015000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,-0.000295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,_result,0,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:31:21.020000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,0.002635,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295675,_result,307,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:57:13.775000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,0.000425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295676,_result,307,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:57:13.780000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,-0.003970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295677,_result,307,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:57:13.785000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,-0.002505,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295678,_result,307,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:57:13.790000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,-0.001528,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295679,_result,307,2026-08-19 10:30:28.932100+00:00,2026-08-19 15:30:28.932100+00:00,2026-08-19 13:57:13.795000+00:00,tail,c28b79975245,/mnt/keb_data/438/Operation1/200/RawData/20260...,438,-0.004458,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
data.columns

Index(['result_x', 'table_x', '_start_x', '_stop_x', '_time', '_measurement_x',
       'host_x', 'path', 'sensor_id', 'xAxis_438', 'yAxis_438', 'zAxis_438',
       'result_y', 'table_y', '_start_y', '_stop_y', '_measurement_y',
       'host_y', 'src', 'active', 'analogIn0', 'flagWord4', 'inputWord0',
       'outputWord0', 'remainingTime', 'stepNr'],
      dtype='str')

In [22]:
cols_to_drop = ['result_x', 'table_x', '_start_x', '_stop_x', '_measurement_x', 'host_x', 'path', 'sensor_id',
                'result_y', 'table_y', '_start_y', '_stop_y', '_measurement_y','host_y', 'src']

data.drop(columns=cols_to_drop, inplace=True)

In [23]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 295680 entries, 0 to 295679
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   _time          295680 non-null  datetime64[us, UTC]
 1   xAxis_438      295680 non-null  float64
 2   yAxis_438      295680 non-null  float64
 3   zAxis_438      295680 non-null  float64
 4   active         279560 non-null  object
 5   analogIn0      279560 non-null  float64
 6   flagWord4      279560 non-null  float64
 7   inputWord0     279560 non-null  float64
 8   outputWord0    279560 non-null  float64
 9   remainingTime  279560 non-null  float64
 10  stepNr         279560 non-null  float64
dtypes: datetime64[us, UTC](1), float64(9), object(1)
memory usage: 24.8+ MB

In [24]:
waMaColumns = ['active', 'analogIn0', 'flagWord4', 'inputWord0', 'outputWord0', 'remainingTime', 'stepNr']

In [25]:
data[waMaColumns] = data[waMaColumns].ffill()

In [26]:
data

,_time,xAxis_438,yAxis_438,zAxis_438,active,analogIn0,flagWord4,inputWord0,outputWord0,remainingTime,stepNr
0,2026-08-19 13:31:21+00:00,-0.002736,0.003148,0.012469,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-08-19 13:31:21.005000+00:00,0.004100,-0.008571,0.000262,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-08-19 13:31:21.010000+00:00,0.004100,-0.004176,-0.000226,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-08-19 13:31:21.015000+00:00,-0.000295,0.006078,0.002703,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-08-19 13:31:21.020000+00:00,0.002635,0.000218,-0.000226,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
295675,2026-08-19 13:57:13.775000+00:00,0.000425,0.003466,0.003398,False,-1.0,33.0,17408.0,0.0,200000.0,1.0
295676,2026-08-19 13:57:13.780000+00:00,-0.003970,-0.001905,0.005351,False,-1.0,33.0,17408.0,0.0,200000.0,1.0
295677,2026-08-19 13:57:13.785000+00:00,-0.002505,-0.007276,0.000468,False,-1.0,33.0,17408.0,0.0,200000.0,1.0
295678,2026-08-19 13:57:13.790000+00:00,-0.001528,0.001513,-0.000020,False,-1.0,33.0,17408.0,0.0,200000.0,1.0
295679,2026-08-19 13:57:13.795000+00:00,-0.004458,0.003466,0.008769,False,-1.0,33.0,17408.0,0.0,200000.0,1.0

In [27]:
valid_wama_cols = [col for col in waMaColumns if col in data.columns]
if valid_wama_cols:
    # Identify rows with NaNs in the specified WaMa columns
    drop_mask = data[valid_wama_cols].isna().any(axis=1)

    if drop_mask.any():
        # Create a temporary copy to group contiguous blocks of dropped rows
        temp_df = data.copy()
        temp_df['_drop_block'] = (drop_mask != drop_mask.shift()).cumsum()

        print(f"Debug: Total rows to delete: {drop_mask.sum()}")
        print("Debug: Identified the following time ranges for deletion:")

        for _, group in temp_df[drop_mask].groupby('_drop_block'):
            start_time = group['_time'].min()
            end_time = group['_time'].max()
            print(f" - {start_time} to {end_time} ({len(group)} rows)")
        data = temp_df[~drop_mask].drop(columns=['_drop_block'])
    else:
        print("Debug: No rows found with missing WaMa values.")

Debug: Total rows to delete: 4483
Debug: Identified the following time ranges for deletion:
 - 2026-08-19 13:31:21+00:00 to 2026-08-19 13:31:44.210000+00:00 (4483 rows)

In [28]:
print(f"Original waMa data shape: {waMaData.shape}")
print(f"Original vibration data shape: {vibrationData.shape}")
print(f"Merged dataset shape: {data.shape}")
print(f"NaN count in waMa columns: {data[waMaColumns].isna().sum().sum()}")

Original waMa data shape: (2935, 15)
Original vibration data shape: (295680, 12)
Merged dataset shape: (291197, 11)
NaN count in waMa columns: 0

In [29]:
data

,_time,xAxis_438,yAxis_438,zAxis_438,active,analogIn0,flagWord4,inputWord0,outputWord0,remainingTime,stepNr
4483,2026-08-19 13:31:44.215000+00:00,0.160156,0.140625,0.991208,False,-1.0,33.0,16384.0,0.0,200000.0,1.0
4484,2026-08-19 13:31:44.220000+00:00,0.159179,0.136230,0.989255,False,-1.0,33.0,16384.0,0.0,200000.0,1.0
4485,2026-08-19 13:31:44.225000+00:00,0.164550,0.133300,0.991697,False,-1.0,33.0,16384.0,0.0,200000.0,1.0
4486,2026-08-19 13:31:44.230000+00:00,0.163574,0.145996,0.979001,False,-1.0,33.0,16384.0,0.0,200000.0,1.0
4487,2026-08-19 13:31:44.235000+00:00,0.160644,0.148925,0.982908,False,-1.0,33.0,16384.0,0.0,200000.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
295675,2026-08-19 13:57:13.775000+00:00,0.000425,0.003466,0.003398,False,-1.0,33.0,17408.0,0.0,200000.0,1.0
295676,2026-08-19 13:57:13.780000+00:00,-0.003970,-0.001905,0.005351,False,-1.0,33.0,17408.0,0.0,200000.0,1.0
295677,2026-08-19 13:57:13.785000+00:00,-0.002505,-0.007276,0.000468,False,-1.0,33.0,17408.0,0.0,200000.0,1.0
295678,2026-08-19 13:57:13.790000+00:00,-0.001528,0.001513,-0.000020,False,-1.0,33.0,17408.0,0.0,200000.0,1.0
295679,2026-08-19 13:57:13.795000+00:00,-0.004458,0.003466,0.008769,False,-1.0,33.0,17408.0,0.0,200000.0,1.0

In [30]:
colsToCompare = ["inputWord0", "outputWord0", "flagWord4"]

In [31]:
for c in colsToCompare:
    prev_val = data[c].shift(1).fillna(0).astype(int)
    data[f"{c}_changed_bits"] = data[c].astype(int) ^ prev_val

In [32]:
data

,_time,xAxis_438,yAxis_438,zAxis_438,active,analogIn0,flagWord4,inputWord0,outputWord0,remainingTime,stepNr,inputWord0_changed_bits,outputWord0_changed_bits,flagWord4_changed_bits
4483,2026-08-19 13:31:44.215000+00:00,0.160156,0.140625,0.991208,False,-1.0,33.0,16384.0,0.0,200000.0,1.0,16384,0,33
4484,2026-08-19 13:31:44.220000+00:00,0.159179,0.136230,0.989255,False,-1.0,33.0,16384.0,0.0,200000.0,1.0,0,0,0
4485,2026-08-19 13:31:44.225000+00:00,0.164550,0.133300,0.991697,False,-1.0,33.0,16384.0,0.0,200000.0,1.0,0,0,0
4486,2026-08-19 13:31:44.230000+00:00,0.163574,0.145996,0.979001,False,-1.0,33.0,16384.0,0.0,200000.0,1.0,0,0,0
4487,2026-08-19 13:31:44.235000+00:00,0.160644,0.148925,0.982908,False,-1.0,33.0,16384.0,0.0,200000.0,1.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295675,2026-08-19 13:57:13.775000+00:00,0.000425,0.003466,0.003398,False,-1.0,33.0,17408.0,0.0,200000.0,1.0,0,0,0
295676,2026-08-19 13:57:13.780000+00:00,-0.003970,-0.001905,0.005351,False,-1.0,33.0,17408.0,0.0,200000.0,1.0,0,0,0
295677,2026-08-19 13:57:13.785000+00:00,-0.002505,-0.007276,0.000468,False,-1.0,33.0,17408.0,0.0,200000.0,1.0,0,0,0
295678,2026-08-19 13:57:13.790000+00:00,-0.001528,0.001513,-0.000020,False,-1.0,33.0,17408.0,0.0,200000.0,1.0,0,0,0
295679,2026-08-19 13:57:13.795000+00:00,-0.004458,0.003466,0.008769,False,-1.0,33.0,17408.0,0.0,200000.0,1.0,0,0,0

In [33]:
for c in colsToCompare:
    prev_val = data[c].shift(1).fillna(0).astype(int)
    for i in range(16):  # Assuming 16-bit integers
        data[f'{c}_bit_{i}_changed'] = (data[f'{c}_changed_bits'] & (1 << i)) != 0
        data[f'{c}_bit_{i}'] = (data[c].astype(int) & (1 << i)) != 0

/tmp/ipykernel_1044/4033313692.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{c}_bit_{i}'] = (data[c].astype(int) & (1 << i)) != 0

In [34]:
data

,_time,xAxis_438,yAxis_438,zAxis_438,active,analogIn0,flagWord4,inputWord0,outputWord0,remainingTime,...,flagWord4_bit_11_changed,flagWord4_bit_11,flagWord4_bit_12_changed,flagWord4_bit_12,flagWord4_bit_13_changed,flagWord4_bit_13,flagWord4_bit_14_changed,flagWord4_bit_14,flagWord4_bit_15_changed,flagWord4_bit_15
4483,2026-08-19 13:31:44.215000+00:00,0.160156,0.140625,0.991208,False,-1.0,33.0,16384.0,0.0,200000.0,...,False,False,False,False,False,False,False,False,False,False
4484,2026-08-19 13:31:44.220000+00:00,0.159179,0.136230,0.989255,False,-1.0,33.0,16384.0,0.0,200000.0,...,False,False,False,False,False,False,False,False,False,False
4485,2026-08-19 13:31:44.225000+00:00,0.164550,0.133300,0.991697,False,-1.0,33.0,16384.0,0.0,200000.0,...,False,False,False,False,False,False,False,False,False,False
4486,2026-08-19 13:31:44.230000+00:00,0.163574,0.145996,0.979001,False,-1.0,33.0,16384.0,0.0,200000.0,...,False,False,False,False,False,False,False,False,False,False
4487,2026-08-19 13:31:44.235000+00:00,0.160644,0.148925,0.982908,False,-1.0,33.0,16384.0,0.0,200000.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295675,2026-08-19 13:57:13.775000+00:00,0.000425,0.003466,0.003398,False,-1.0,33.0,17408.0,0.0,200000.0,...,False,False,False,False,False,False,False,False,False,False
295676,2026-08-19 13:57:13.780000+00:00,-0.003970,-0.001905,0.005351,False,-1.0,33.0,17408.0,0.0,200000.0,...,False,False,False,False,False,False,False,False,False,False
295677,2026-08-19 13:57:13.785000+00:00,-0.002505,-0.007276,0.000468,False,-1.0,33.0,17408.0,0.0,200000.0,...,False,False,False,False,False,False,False,False,False,False
295678,2026-08-19 13:57:13.790000+00:00,-0.001528,0.001513,-0.000020,False,-1.0,33.0,17408.0,0.0,200000.0,...,False,False,False,False,False,False,False,False,False,False
295679,2026-08-19 13:57:13.795000+00:00,-0.004458,0.003466,0.008769,False,-1.0,33.0,17408.0,0.0,200000.0,...,False,False,False,False,False,False,False,False,False,False